/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:a5fd98ea-52cf-4230-8d1f-dca442db4443",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_16xxGLvBw",
    "aws_user_pools_web_client_id": "6e5a4qjbr5ucd9djbdmpcqdvjo",
    "oauth": {}
};


export default awsmobile;
